name: workflow

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 1200
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies (prod)
        run: yarn install --frozen-lockfile --production

      - name: Run Tests (JEST)
        run: yarn test --ci --silent --testPathIgnorePatterns=experimental
        env:
          CI: true
          TEST: ${{ secrets.TEST }} 

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          TEST: ${{ TEST }}
      - run: node -e "console.log(process.env.TEST)"
