name: Rotate Mapbox Token

on:
  workflow_dispatch:

jobs:
  rotate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set new token from GitHub Secret
        env:
          NEW_TOKEN: ${{ secrets.MAPBOX_MANAGEMENT_TOKEN }}
        run: |
          echo "Replacing token in mapbox/public/config.json with the GitHub Secret token"
          sed -i "s/\"mapboxToken\": \".*\"/\"mapboxToken\": \"$NEW_TOKEN\"/" mapbox/public/config.json

      - name: Commit updated token
        uses: EndBug/add-and-commit@v9
        with:
          message: "Rotated Mapbox token"
          add: "mapbox/public/config.json"
