name: Rotate Mapbox Token

on:
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace token in config.json with base64-encoded secret
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: |
          cp mapbox/public/config.template.json mapbox/public/config.json
          ENCODED_TOKEN=$(echo -n "$MAPBOX_TOKEN" | base64)
          sed -i "s|\${MAPBOX_TOKEN}|$ENCODED_TOKEN|g" mapbox/public/config.json


      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'mapbox/public/config.json'
          message: 'Rotate Mapbox token'
